#!/usr/bin/env zsh
if type yaourt &>/dev/null ; then
	#
	# Yaourt aliases for ArchLinux and friends
	#
	alias yaconf='yaourt -C'
	alias yain='yaourt -S'
	alias yains='yaourt -U'
	alias yainsd='yaourt -S --asdeps'
	alias yaloc='yaourt -Qi'
	alias yalocs='yaourt -Qs'
	alias yalst='yaourt -Qe'
	alias yamir='yaourt -Syy'
	alias yaorph='yaourt -Qtd'
	alias yare='yaourt -R'
	alias yarem='yaourt -Rns'
	alias yarep='yaourt -Si'
	alias yareps='yaourt -Ss'
	alias yasu='yaourt --sucre'
	alias yaupg='yaourt -Syua'
fi
