#!/usr/bin/env bash

# Read current PWM frequency and set delta and cap:
#(separate file is unneded now since I set the PWM register in the module
# install hook, so it updates max_brightness correctly)
#FREQ_FILE='/tmp/pwmfreq'

FREQ_FILE='/sys/class/backlight/intel_backlight/max_brightness'
if [[ -r "${FREQ_FILE}" ]]; then
	BL_CAP="$(<${FREQ_FILE})"
else
	BL_CAP="$(</sys/class/backlight/intel_backlight/max_brightness)"
fi
CUR_BRIGHT=$(</sys/class/backlight/intel_backlight/brightness)

up() {
    NEW_BRIGHT=$(( CUR_BRIGHT + BL_DELTA ))
}

down() {
    NEW_BRIGHT=$(( CUR_BRIGHT - BL_DELTA ))

    # Avoid total darkness:
    (( NEW_BRIGHT < 1 )) && NEW_BRIGHT="1"
}

case $2 in
    full)
        BL_DELTA=$(( BL_CAP / 9 ))
        ;;
    half)
        BL_DELTA=$(( BL_CAP / 18 ))
        ;;
esac

case $1 in
    down)
        down
        ;;
    up)
        up
        ;;
esac
# Avoid overbrights:
(( NEW_BRIGHT > BL_CAP )) && NEW_BRIGHT="${BL_CAP}"

echo "${NEW_BRIGHT}" | sudo tee /sys/class/backlight/intel_backlight/brightness

notify-send -t 500 "Brightness: $(( NEW_BRIGHT * 100 / BL_CAP))%"
