#!/usr/bin/env bash

# Read current PWM frequency and set delta and cap:
PWMFREQ="$(cat /tmp/pwmfreq)"
BL_CAP="$PWMFREQ"
BL_DELTA=$(( BL_CAP / 9 ))

up() {
    CUR_BRIGHT=$(</sys/class/backlight/intel_backlight/brightness)
    NEW_BRIGHT=$(( CUR_BRIGHT + BL_DELTA ))

    # Avoid overbrights so there's no need
    # to decrease brightness all the way from 900%.
    [[ "${NEW_BRIGHT}" -gt "${BL_CAP}" ]] && NEW_BRIGHT="${BL_CAP}"

    echo "${NEW_BRIGHT}" | sudo tee /sys/class/backlight/intel_backlight/brightness
}

down() {
    CUR_BRIGHT=$(</sys/class/backlight/intel_backlight/brightness)
    NEW_BRIGHT=$(( CUR_BRIGHT - BL_DELTA ))

    # Avoid total darkness:
    [[ "${NEW_BRIGHT}" -lt "1" ]] && NEW_BRIGHT="1"
    # Added this because switching to hi-freq backlight
    # usually results in brightness set to something like 250%
    [[ "${NEW_BRIGHT}" -gt "${BL_CAP}" ]] && NEW_BRIGHT="${BL_CAP}"

    echo "${NEW_BRIGHT}" | sudo tee /sys/class/backlight/intel_backlight/brightness
}

case $1 in
    down)
        down
        ;;
    up)
        up
        ;;
esac

notify-send -t 500 "Brightness: $(( NEW_BRIGHT * 100 / BL_CAP))%"
