#!/usr/bin/env bash

## Load config file:
CFGDIR="${XDG_CONFIG_HOME:-$HOME/.config}/herbstluftwm"
. "${CFGDIR}/global.conf"
## Also load color config and current theme opts:
. "${CFGDIR}/themes.d/current/colors.conf"
. "${CFGDIR}/themes.d/current/opts.conf"

hc() { "${herbstclient_command[@]:-herbstclient}" "$@" ;}
get_volume() { "${HLPDIR}/volume" get ;}

monitor="${1:-0}"
geometry=$(herbstclient monitor_rect "$monitor" | $AWK "{printf \"%sx%s+%s+%s\"values,\$3,\"${PANELHEIGHT}\",\$1,\$2;}")
[[ -z "$geometry" ]] && echo "Invalid monitor $monitor" && exit 1

bgcolor="${IN_FRAMEBR}"
selbg="${AC_WINBR}"
selfg="${SE_TEXT}"

fifo_events="${PANEL_FIFO}.${monitor}"
if [[ "$2" = "debug" ]]; then
    [[ -e "$fifo_events" ]] && rm "$fifo_events"
    mkfifo -m600 "$fifo_events"
else
    [[ -p "$fifo_events" ]] || notify-send -u critical "Panel error!" "No FIFO found!"
fi

# Pad the screen to panel height:
hc pad "$monitor" "$PANELHEIGHT"

## Read the taglist and create the tag widget contents:
gentagline () {
    # Switch the font to glyphs:
    tagline="%{T2}"
    # Read the tag list:
    # IFS=$'\t' read -ra tags <<< "$(hc tag_status $monitor)"
    tags=( $(hc tag_status $monitor) )
    ## Tag statuses:
    #  '#' -- Tag is active and focused on current monitor;
    #  '+' -- Tag is active on current monitor,
    #         but another monitor is focused;
    #  ':' -- Tag is not active, but contains windows;
    #  '!' -- Tag contains an urgent window.
    for i in "${!tags[@]}" ; do
        case "${tags[i]:0:1}" in
            '#' ) tagcolor="%{B$selbg}%{F$selfg}";;
            '+' ) tagcolor="%{B#9CA668}%{F$selfg}";;
            ':' ) tagcolor="%{B-}%{F${AC_TEXT}}";;
            '!' ) tagcolor="%{B${UR_WINBR}}%{F$selfg}";;
            *   ) tagcolor="%{B-}%{F${IN_TEXT}}";;
        esac
        tagline+="${tagcolor}%{A:herbstclient chain .-. focus_monitor \"${monitor}\" .-. use \"${tags[i]:1}\":} ${tag_icons[i]} %{A}"
    done
    #  Switch font back to text:
    tagline+="%{T1}"
}

parsecmd () {
    #  The event and its arguments are read into the array cmd, then action is taken
    #  depending on the event name. "Special" events
    #  (quit_panel/togglehidepanel/reload) are also handled here.
    cmd="$1"
    case "${cmd[0]}" in
        tag*       ) gentagline;;
        conky      ) conky="${cmd[1]}";;
        quit_panel ) exit;;
        reload     )
            pkill -P $$
            rm "$fifo_events"
            exit
            ;;
        *changed   ) windowtitle="${cmd[2]}";;
        layout     ) layout="${cmd[1]}";;
        volume     ) volume=$(printf "%b" "${cmd[1]}");;
    esac
}

if [ "$2" = "debug" ]; then
## Feed the event loop:
#  I feed the panel via herbstclient hooks.
#  I also pipe the event list via awk to get rid of identical events (like
#  redundant conky updates).
herbstclient --idle | $AWK '$0 != l { print ; l=$0 ; fflush(); }' > "$fifo_events" &
fi

## Pre-fill data:
gentagline
conky=""
layout="$(skb -1)"
windowtitle="Welcome home."
volume=$(printf "%b" "$(get_volume)")
SEPARATOR="%{B-}%{F$selbg}|%{F-}"

## Here comes the event loop:
while IFS=$'\t' read -ra cmd; do
    # Parse the event:
    parsecmd "${cmd}"
    # Draw tags and window title:
    printf "%s" "${tagline}${SEPARATOR} ${windowtitle//%{/% {}"
    # Draw info stuff on the right side of the panel and finish the line:
    printf "%s\n" "%{r} $layout $SEPARATOR $volume $SEPARATOR $conky "
done < "$fifo_events" |\
    lemonbar -g "${geometry}" \
             -f "${TEXTFONT}" -f "${GLYPHFONT}" \
             -B "$bgcolor" -F "${AC_TEXT}"
