#!/usr/bin/env bash
. "${HOME}/.config/herbstluftwm/themes.d/current/colors.conf"
color2code () {
    RAWVALUE=$(tr -d '"#' <<< $1)
    DECVAL="$(for HEXVAL in $(grep -o .. <<< $RAWVALUE ) ; do
        printf "%d;" "0x$HEXVAL"
    done)"
    printf "\x1b[38;2;%sm████\x1b[0m" "${DECVAL::-1}"
}
echo "Frame borders:"
echo -e "$(color2code $IN_FRAMEBR)\t$(color2code $AC_FRAMEBR)"
echo -e "$(color2code $IN_FRAMEBG)\t$(color2code $AC_FRAMEBG)"
echo "Window borders:"
echo -e "$(color2code $IN_WINBR)\t$(color2code $AC_WINBO)\t$(color2code $UR_WINBR)"
echo -e "$(color2code $IN_WINBR)\t$(color2code $AC_WINBR)\t$(color2code $UR_WINBR)"
echo -e "$(color2code $AL_WINBI)\t$(color2code $AC_WINBI)\t$(color2code $AL_WINBI)"
