#!/usr/bin/env bash
. "${HOME}/.config/herbstluftwm/colors.conf"
color2code () {
    RAWVALUE=$(tr -d '"#' <<< $1)
    DECVAL="$(for HEXVAL in $(grep -o .. <<< $RAWVALUE ) ; do
        printf "%d;" "0x$HEXVAL"
    done)"
    printf "\x1b[38;2;%sm████\x1b[0m" "${DECVAL::-1}"
}
echo "Frame borders:"
echo -e "$(color2code $FBR_INACT)\t$(color2code $FBR_ACTIV)"
echo -e "$(color2code $FBG_INACT)\t$(color2code $FBG_ACTIV)"
echo "Window borders:"
echo -e "$(color2code $WBO_INACT)\t$(color2code $WBO_ACTIV)\t$(color2code $WBO_URGNT)"
echo -e "$(color2code $WBR_INACT)\t$(color2code $WBR_ACTIV)\t$(color2code $WBR_URGNT)"
echo -e "$(color2code $WBI_GLOBL)\t$(color2code $WBI_ACTIV)\t$(color2code $WBI_GLOBL)"
