#!/usr/bin/env bash

##############################################
## Tray script for places where it's needed ##
## Uses magic fork function to kickstart    ##
## everything and die in peace.             ##
##############################################

function fork() {
	setsid "$@" >& /dev/null &
	sleep 0.01
}

## Load config file:
CFGDIR="${XDG_CONFIG_HOME:-$HOME/.config}/herbstluftwm"
. "${CFGDIR}/global.conf"
## Also load color config and current theme opts:
. "${CFGDIR}/themes.d/current/colors.conf"
. "${CFGDIR}/themes.d/current/opts.conf"

## In some cases trayer-srg's binary is called
## "trayer-srg", not "trayer".
for command in trayer trayer-srg ; do
    type "${command}" >/dev/null 2>&1 && TRAYER_COMMAND="$(which ${command})"
done

## Run only if found working trayer binary.
if [[ -x "${TRAYER_COMMAND}" ]]; then
    pkill "trayer"
    pgrep lemonbar &>/dev/null || sleep 2
    fork "${TRAYER_COMMAND}" \
            --edge top --align left --widthtype request \
            --heighttype pixel --height "${PANELHEIGHT}" --transparent true \
            --alpha 0 --tint "0x${IN_FRAMEBR//#/}" \
            --distancefrom left --distance 174
    # Trying to switch to NetworkManager-dmenu.
    # pkill 'nm-applet' >/dev/null
    # fork nm-applet
else
    notify-send -u critical "Tray error" "Trayer binary not found."
fi
