#!/usr/bin/env bash
. "${CFGDIR:-$HOME/.config/herbstluftwm}/themes.d/current/colors.conf"

################################################
## This script controls the volume.           ##
## Works with ALSA and PulseAudio.            ##
## Also outputs current volume to HLWM panel. ##
################################################

parse_volume() {
    [ "${CUR_VOLUME}" = "Mute" ] && OUTPUT="%{F${IN_TEXT}}\ue04f%{F-}" && return 0
    (( CUR_VOLUME>=60 )) && OUTPUT="\ue05d ${CUR_VOLUME}%" && return 0
    (( CUR_VOLUME>=30 && CUR_VOLUME<60 )) && OUTPUT="%{F${MI_TEXT}}\ue050 %{F-}${CUR_VOLUME}%" && return 0
    (( CUR_VOLUME<30 )) && OUTPUT="%{F${IN_TEXT}}\ue04e %{F-}${CUR_VOLUME}%" && return 0
}

get_volume() {
    CUR_VOLUME=$(amixer get Master | awk '/Front Left:.+/ {print $6=="[off]"?"Mute":$5}' | tr -d '[%]')
    parse_volume
    printf "%s" "$OUTPUT"
}

case $1 in
    down)
        amixer -q set Master 2%- unmute
        ;;
    up)
        amixer -q set Master 2%+ unmute
        ;;
    mute)
        amixer -q set Master toggle
        ;;
    get)
        get_volume && exit 0
        ;;
esac
herbstclient emit_hook volume "$(get_volume)"
