#!/usr/bin/env zsh

if type brew &>/dev/null && [[ -d /opt/homebrew/opt/nvm ]]; then
    [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"    # This loads nvm
    [ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"    # This loads nvm bash_completion
fi
