#!/usr/bin/env bash
CONKY_FILE="/tmp/conky.out"
[[ -f "${CONKY_FILE}" ]] || echo "" > "${CONKY_FILE}"
until pgrep conky >/dev/null; do
    sleep 2
done
while inotifywait -e close $CONKY_FILE >/dev/null 2>&1; do
    herbstclient emit_hook conky "$(<${CONKY_FILE})"
done
