#!/usr/bin/env bash

## Get display list:
int_display="$(xrandr | awk '$2 == "connected" && $1 ~ "eDP" {print $1}')"
ext_display="$(xrandr | awk '$2 ~ "(dis)?connected" && $1 !~ "eDP" {print $1":"$2}')"
ext_display_name="${ext_display%:*}"
ext_display_status="${ext_display#*:}"

SCREEN_OPTS="Auto
Laptop
Desktop"

OPT="${1^:-Auto}"

[[ -z "${OPT:-}" ]] && OPT="$(rofi -p 'Screen setup:' -dmenu <<< ${SCREEN_OPTS})"

laptop() {
    xrandr --output "${ext_display_name}" --off
}

desktop() {
    xrandr --output "${ext_display_name}" --above "${int_display}" --noprimary --auto
    xrandr --output "${int_display}" --primary
}


case "${OPT}" in
    'Laptop') laptop;;
    'Desktop') desktop;;
    *)
        if [[ -n "${ext_display_status:-disconnected}" ]]; then
            desktop
        else
            laptop
        fi ;;
esac

[[ "${XDG_SESSION_DESKTOP}" = herbstluftwm && "${2:-}" = "" ]] && herbstclient reload
[[ "${XDG_SESSION_DESKTOP}" = bspwm && "${2:-}" = "" ]] && ~/.config/bspwm/bspwmrc
