#!/usr/bin/env bash

SSHOT_DIR="$HOME/Pictures/Scrots"
SSHOT_OPTS="Full Screen
Select Window/Area
Select Window (Shadowed)"
OUT_OPTS="File
Clipboard"

## Get launch options:
while getopts "fjwd:" opt; do
    case $opt in
        d) DELAY="${OPTARG}";;
        f) OPT="Full Screen"
           OUT="File";;
        w) OPT="Select Window/Area"
           OUT="File";;
        j) OPT="Select Window/Area"
           OUT="Clipboard";;
    esac
done

## Raise menu if no options given:
[[ -n "${OPT}" ]] || OPT="$(rofi -p 'Screenshot:' -dmenu <<< ${SSHOT_OPTS})"
[[ "${?:-0}" = "0" ]] || exit 0
case "${OPT}" in
    "Full Screen")
	sleep 1
        DATA="$(base64 < <(maim -d ${DELAY:-0}))";;
    "Select Window/Area")
        DATA="$(base64 < <(maim -s -n 1 -d ${DELAY:-0}))";;
    "Select Window (Shadowed)")
        DATA="$(base64 < <(maim -s -n 1 -t 9999999 | convert - \( +clone -background black -shadow 99x5+0+0 \) +swap -background none -layers merge +repage - ))";;
esac

## Raise menu if no options given:
[[ -n "${OUT}" ]] || OUT="$(rofi -p 'Save Screenshot to:' -dmenu <<< ${OUT_OPTS})"
[[ "${?:-0}" = "0" ]] || exit 0
case "${OUT}" in
    "File")
        OUT_FILE="${SSHOT_DIR}/$(date '+%Y%m%d_%H%M%S').png"
        base64 -d <<< "${DATA}" > "${OUT_FILE}"
        notify-send -a "Scrot" -i "${OUT_FILE}" "Screenshot taken!" "Saved as \"${OUT_FILE##*/}\".";;
    "Clipboard")
        base64 -d <<< "${DATA}" | xclip -selection clipboard -t image/png;;
esac
