#!/usr/bin/env bash
#:'##::::'##:'##:::::::'##:::::'##:'##::::'##:
#: ##:::: ##: ##::::::: ##:'##: ##: ###::'###:
#: ##:::: ##: ##::::::: ##: ##: ##: ####'####:
#: #########: ##::::::: ##: ##: ##: ## ### ##:
#: ##.... ##: ##::::::: ##: ##: ##: ##. #: ##:
#: ##:::: ##: ##::::::: ##: ##: ##: ##:.:: ##:
#: ##:::: ##: ########:. ###. ###:: ##:::: ##:
#:..:::::..::........:::...::...:::..:::::..::
# export HLWM_DEBUG=true

## Write debug log if needed:
if [[ "${HLWM_DEBUG}" = "true" ]]; then
    set -x
    exec > "/tmp/hlwm-$(whoami)-wm.log" 2>&1
fi

## Load config file and emit 'reload' hook:
CFGDIR="${XDG_CONFIG_HOME:-$HOME/.config}/herbstluftwm"
. "${CFGDIR}/global.conf"
hc emit_hook reload

## Laptop additions:
if [[ "${PEKO}" = "laptop-home" ]]; then
    # Add user-fonts to XFLD and rehash fontdirs:
    xset +fp /home/spijet/.fonts
    xset fp rehash
fi

##  Set up tags:
#   First, add all configured tags:
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
done
#   Then switch to the first tag and merge it with 'default' one:
hc use "${tag_names[0]}"
hc merge_tag default "${tag_names[0]}"
#   Commit the changes:
hcc

##  Load theme, keybinds and rules:
for CONFIG in "theme.conf" "keybinds.conf" "rules.conf"; do
    . "${CFGDIR}/${CONFIG}"
    hcc
done

# Unlock, just to be sure:
hc unlock
herbstclient set tree_style "${TREE_STYLE}"
# Do multi monitor setup:
herbstclient detect_monitors

# Send the commandchain to hlwm in one command and load the savestate:
hcc
[[ -f "${SAVESTATE}" ]] && "${HLPDIR}/loadstate" "${SAVESTATE}"

#  Fill the monitor list (for panel):
#  (no quoting here since I want to expand one sting to N monitors)
MONITORS=( $(herbstclient list_monitors | cut -d: -f1) )
for monitor in ${MONITORS[@]} ; do
    hc pad "$monitor" "$PANELHEIGHT"
done

# Start up panel and system tray:
pkill -U "${UID}" -f barabara ; barabara &
pkill -U "${UID}" -f trayer ; /home/spijet/.dotfiles/scripts/tray &

## Fork all running processes away and die peacefully:
disown
