#!/usr/bin/env bash

#:'##::::'##:'##:::::::'##:::::'##:'##::::'##:
#: ##:::: ##: ##::::::: ##:'##: ##: ###::'###:
#: ##:::: ##: ##::::::: ##: ##: ##: ####'####:
#: #########: ##::::::: ##: ##: ##: ## ### ##:
#: ##.... ##: ##::::::: ##: ##: ##: ##. #: ##:
#: ##:::: ##: ##::::::: ##: ##: ##: ##:.:: ##:
#: ##:::: ##: ########:. ###. ###:: ##:::: ##:
#:..:::::..::........:::...::...:::..:::::..::

## Load config file:
CFGDIR="${XDG_CONFIG_HOME:-$HOME/.config}/herbstluftwm"
. "${CFGDIR}/global.conf"

hc emit_hook reload

## Laptop additions:
if [[ "${PEKO}" = "laptop-home" ]]; then
    # Set screen refresh rate.
    xrandr -r 48 &
    #
    # Set Intel backlight PWM rate.
    # See helper code for details.
    "${HLPDIR}/pwmfreq" fix &
    #
    # Add user-fonts to XFLD.
    xset +fp /home/spijet/.fonts
    # Also, Tewi. I love Tewi.
    xset +fp /usr/share/fonts/tewi-font
    # Rehash fontdirs.
    xset fp rehash
fi

## Set the wallpaper(s):
if type nitrogen ; then
	nitrogen --restore &
else
	~/.fehbg &
fi

# New hlwm function that allows making cleaner version of run_once.
if herbstclient silent new_attr bool my_not_first_autostart ; then
    compton &
    kbdd &
    "${HLPDIR}/xkbmon" &
    type conky >/dev/null 2>&1 && "${HLPDIR}/hc-conky" &
fi

# Remove default tag (merge into first)
hc rename default "${tag_names[0]}"

# Populate tag keybinds:
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
done

## Load keybinds:
. "${CFGDIR}/keybinds.conf"

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_normal_color '#101010'
hc set frame_border_active_color '#222222'
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#345F0C'
hc set frame_border_width 1
hc set always_show_frame 1
hc set frame_bg_transparent 1
hc set frame_transparent_width 5
hc set frame_gap 6

hc attr theme.active.color '#9fbc00'
hc attr theme.normal.color '#454545'
hc attr theme.urgent.color '#ff0675'
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 3
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#3E4A00'
hc attr theme.active.outer_color '#3E4A00'
hc attr theme.background_color '#141414'

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0
hc set focus_follows_mouse 1

##  Load HLWM rules:
. "${CFGDIR}/rules.conf"

# unlock, just to be sure
hc unlock

herbstclient set tree_style "${TREE_STYLE}"

# Do multi monitor setup:
hc detect_monitors

# Send the commandchain to hlwm in one command,
# because we're fast!
# (No quoting here because args should be separated, IIRC)
herbstclient $cmds &

#   Load the savestate:
[[ -f "${SAVESTATE}" ]] && "${HLPDIR}/loadstate" "${SAVESTATE}"

## Prepare panel:
#  (no quoting here since I want to expand one sting to N monitors)
MONITORS=( $(herbstclient list_monitors | cut -d: -f1) )
#  Kill any herbstclient running before us:
pkill -cxf 'herbstclient --idle'
FIFOS=""
#  Create event pipes:
for monitor in ${MONITORS[@]} ; do
    FIFO="/tmp/panelevents.${monitor}"
    [ -e "$FIFO" ] && rm "$FIFO"
    mkfifo -m600 "$FIFO"
    FIFOS+="${FIFO} "
done
## Fill them with data from herbstclient:
#  (no quoting here since I want to expand one sting to N monitors)
#  I also pipe the event list via awk to get rid of identical events (like
#  redundant conky updates).
if [ "${#MONITORS[@]}" -gt "1" ]; then
    herbstclient --idle | $AWK '$0 != l { print ; l=$0 ; fflush(); }' | tee $FIFOS &
else # No need for `tee` for one monitor.
    herbstclient --idle | $AWK '$0 != l { print ; l=$0 ; fflush(); }' > $FIFOS &
fi

[[ -x "$PANEL" ]] || PANEL="/etc/xdg/herbstluftwm/panel.sh"
for monitor in ${MONITORS[@]} ; do
    # start it on each monitor
    "$PANEL" "$monitor" &
done
[[ "${PEKO}" = "laptop"* ]] && "${HLPDIR}/tray" &
